# Generated by Django 5.0.4 on 2024-05-08 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_dadosmedico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadosmedico',
            old_name='srm',
            new_name='crm',
        ),
    ]
